# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 115a2d14bb13552ba83ccec2326e3228cb683ad1125b8f4a925008857f7c4f7251a2ea7dcc1d4ac861b4e3eee0bf6ff024d8bf66e8e98732f6cf7a816c6662ce

test:
  secret_key_base: a32dc12d91876f38611d921d586a6c425266f352bebcc275dc74a4e7fe76f97b3b4e16fc05750f7f8577f099ee2ee72291a39c48782f1c868dafb31aa7c84434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
